public class func{
  public static void main(String arg[]){

    String[] code = {"aa", "hy", "or", "ab", "hz", "os", "af", "id", "pa", "ak", "ig", "pl", "am", "ii", "ps", "an", "ik", "pt", "ar", "io", "qu", "as", "is", "rm", "av", "it", "rn", "ay", "iu", "ro", "az", "ja", "ru", "ba", "jv", "rw", "be", "ka", "sa", "bg", "kg", "sc", "bh", "ki", "sd", "bi", "kj", "se", "bm", "kk", "sg", "bn", "kl", "si", "bo", "km", "sk", "br", "kn", "sl", "bs", "ko", "sm", "ca", "kr", "sn", "ce", "ks", "so", "ch", "ku", "sq", "co", "kv", "sr", "cr", "kw", "ss", "cs", "ky", "st", "cv", "lb", "su", "cy", "lg", "sv", "da", "li", "sw", "de", "ln", "ta", "dv", "lo", "te", "dz", "lt", "tg", "ee", "lu", "th", "el", "lv", "ti", "en", "mg", "tk", "es", "mh", "tl", "et", "mi", "tn", "eu", "mk", "to", "fa", "ml", "tr", "ff", "mn", "ts", "fi", "mr", "tt", "fj", "ms", "tw", "fo", "mt", "ty", "fr", "my", "ug", "fy", "na", "uk", "ga", "nb", "ur", "gd", "nd", "uz", "gl", "ne", "ve", "gn", "ng", "vi", "gu", "nl", "wa", "gv", "nn", "wo", "ha", "no", "xh", "he", "nr", "yi", "hi", "nv", "yo", "ho", "ny", "za", "hr", "oc", "zh", "ht", "oj", "zu", "hu", "om"};
    String[] lang = {"Afar", "Armenian", "Oriya", "Abkhaz", "Herero", "Ossetian", "Afrikaans", "Indonesian", "Panjabi", "Akan", "Igbo", "Polish", "Amharic", "Nuosu", "Pashto", "Aragonese", "Inupiaq", "Portuguese", "Arabic", "Ido", "Quechua", "Assamese", "Icelandic", "Romansh", "Avaric", "Italian", "Kirundi", "Aymara", "Inuktitut", "Romanian", "Azerbaijani", "Japanese", "Russian", "Bashkir", "Javanese", "Kinyarwanda", "Belarusian", "Georgian", "Sanskrit", "Bulgarian", "Kongo", "Sardinian", "Bihari", "Kikuyu", "Sindhi", "Bislama", "Kwanyama", "Northern Sami", "Bambara", "Kazakh", "Sango", "Bengali", "Kalaallisut", "Sinhala", "Tibetan", "Khmer", "Slovak", "Breton", "Kannada", "Slovenian", "Bosnian", "Korean", "Samoan", "Catalan", "Kanuri", "Shona", "Chechen", "Kashmiri", "Somali", "Chamorro", "Kurdish", "Albanian", "Corsican", "Komi", "Serbian", "Cree", "Cornish", "Swati", "Czech", "Kyrgyz", "Southern Sotho", "Chuvash", "Luxembourgish", "Sundanese", "Welsh", "Ganda", "Swedish", "Danish", "Limburgish", "Swahili", "German", "Lingala", "Tamil", "Divehi", "Lao", "Telugu", "Dzongkha", "Lithuanian", "Tajik", "Ewe", "Luba-Katanga", "Thai", "Greek", "Latvian", "Tigrinya", "English", "Malagasy", "Turkmen", "Spanish", "Marshallese", "Tagalog", "Estonian", "Māori", "Tswana", "Basque", "Macedonian", "Tonga", "Persian", "Malayalam", "Turkish", "Fula", "Mongolian", "Tsonga", "Finnish", "Marathi", "Tatar", "Fijian", "Malay", "Twi", "Faroese", "Maltese", "Tahitian", "French", "Burmese", "Uighur", "Western Frisian", "Nauru", "Ukrainian", "Irish", "Norwegian Bokmål", "Urdu", "Scottish Gaelic", "North Ndebele", "Uzbek", "Galician", "Nepali", "Venda", "Guaraní", "Ndonga", "Vietnamese", "Gujarati", "Dutch", "Walloon", "Manx", "Norwegian Nynorsk", "Wolof", "Hausa", "Norwegian", "Xhosa", "Hebrew", "South Ndebele", "Yiddish", "Hindi", "Navajo", "Yoruba", "Hiri Motu", "Chichewa", "Zhuang", "Croatian", "Occitan", "Chinese", "Haitian", "Ojibwe", "Zulu", "Hungarian", "Oromo"};
    for (int i = 0; i < 176; i++) {
      System.out.println("<option value=\"" + code[i] +"\">" + lang[i] + "</option>");
    }
  }
}


/*
"aa", "hy", "or", "ab", "hz", "os", "af", "id", "pa", "ak", "ig", "pl", "am", "ii", "ps", "an", "ik", "pt", "ar", "io", "qu", "as", "is", "rm", "av", "it", "rn", "ay", "iu", "ro", "az", "ja", "ru", "ba", "jv", "rw", "be", "ka", "sa", "bg", "kg", "sc", "bh", "ki", "sd", "bi", "kj", "se", "bm", "kk", "sg", "bn", "kl", "si", "bo", "km", "sk", "br", "kn", "sl", "bs", "ko", "sm", "ca", "kr", "sn", "ce", "ks", "so", "ch", "ku", "sq", "co", "kv", "sr", "cr", "kw", "ss", "cs", "ky", "st", "cv", "lb", "su", "cy", "lg", "sv", "da", "li", "sw", "de", "ln", "ta", "dv", "lo", "te", "dz", "lt", "tg", "ee", "lu", "th", "el", "lv", "ti", "en", "mg", "tk", "es", "mh", "tl", "et", "mi", "tn", "eu", "mk", "to", "fa", "ml", "tr", "ff", "mn", "ts", "fi", "mr", "tt", "fj", "ms", "tw", "fo", "mt", "ty", "fr", "my", "ug", "fy", "na", "uk", "ga", "nb", "ur", "gd", "nd", "uz", "gl", "ne", "ve", "gn", "ng", "vi", "gu", "nl", "wa", "gv", "nn", "wo", "ha", "no", "xh", "he", "nr", "yi", "hi", "nv", "yo", "ho", "ny", "za", "hr", "oc", "zh", "ht", "oj", "zu", "hu", "om"
*/

/*
"Afar", "Armenian", "Oriya", "Abkhaz", "Herero", "Ossetian", "Afrikaans", "Indonesian", "Panjabi", "Akan", "Igbo", "Polish", "Amharic", "Nuosu", "Pashto", "Aragonese", "Inupiaq", "Portuguese", "Arabic", "Ido", "Quechua", "Assamese", "Icelandic", "Romansh", "Avaric", "Italian", "Kirundi", "Aymara", "Inuktitut", "Romanian", "Azerbaijani", "Japanese", "Russian", "Bashkir", "Javanese", "Kinyarwanda", "Belarusian", "Georgian", "Sanskrit", "Bulgarian", "Kongo", "Sardinian", "Bihari", "Kikuyu", "Sindhi", "Bislama", "Kwanyama", "Northern Sami", "Bambara", "Kazakh", "Sango", "Bengali", "Kalaallisut", "Sinhala", "Tibetan", "Khmer", "Slovak", "Breton", "Kannada", "Slovenian", "Bosnian", "Korean", "Samoan", "Catalan", "Kanuri", "Shona", "Chechen", "Kashmiri", "Somali", "Chamorro", "Kurdish", "Albanian", "Corsican", "Komi", "Serbian", "Cree", "Cornish", "Swati", "Czech", "Kyrgyz", "Southern Sotho", "Chuvash", "Luxembourgish", "Sundanese", "Welsh", "Ganda", "Swedish", "Danish", "Limburgish", "Swahili", "German", "Lingala", "Tamil", "Divehi", "Lao", "Telugu", "Dzongkha", "Lithuanian", "Tajik", "Ewe", "Luba-Katanga", "Thai", "Greek", "Latvian", "Tigrinya", "English", "Malagasy", "Turkmen", "Spanish", "Marshallese", "Tagalog", "Estonian", "Māori", "Tswana", "Basque", "Macedonian", "Tonga", "Persian", "Malayalam", "Turkish", "Fula", "Mongolian", "Tsonga", "Finnish", "Marathi", "Tatar", "Fijian", "Malay", "Twi", "Faroese", "Maltese", "Tahitian", "French", "Burmese", "Uighur", "Western Frisian", "Nauru", "Ukrainian", "Irish", "Norwegian Bokmål", "Urdu", "Scottish Gaelic", "North Ndebele", "Uzbek", "Galician", "Nepali", "Venda", "Guaraní", "Ndonga", "Vietnamese", "Gujarati", "Dutch", "Walloon", "Manx", "Norwegian Nynorsk", "Wolof", "Hausa", "Norwegian", "Xhosa", "Hebrew", "South Ndebele", "Yiddish", "Hindi", "Navajo", "Yoruba", "Hiri Motu", "Chichewa", "Zhuang", "Croatian", "Occitan", "Chinese", "Haitian", "Ojibwe", "Zulu", "Hungarian", "Oromo"
*/
